<?php echo $this->doctype(); ?>

<html lang = "pl">
    
    <head>
        
        <?php 
            echo $this->headMeta()."\n";
            echo $this->headTitle()."\n";
            echo $this->headLink()."\n";
            echo $this->headScript()."\n";
        ?>
        
    </head>
    
    <body>
        
        <div id = "content" style = "width: 600px;margin: 0 auto;text-align: center;">
            <?php echo $this->layout()->content; ?>
        </div>
        
    </body>
    
</html>