<style>
    td
    {
        padding: 3px;
    }
    
    tr
    {
        border: solid thin #c5dbec;
    }
</style>

<!-- Instantiate Feather -->
<script type="text/javascript">
        var featherEditor = new Aviary.Feather({
            apiKey: 'd9f1a41e0',
            apiVersion: 2,
            tools: 'all',
            language: 'pl',
            onSave: function(imageID, newURL) {
                var img = document.getElementById(imageID);
                img.src = newURL;
            }
        });

        function launchEditor(id) {
            featherEditor.launch({
                image: id
            });
            return false;
        }
        
        $(function(){
           $('.counter').counter({
              'backUrl' : '<?php echo $this->baseUrl('public/styles/ui/images/digits2.png') ?>',
              'digitsNumber' : 4
           });
        });
        
        function update(object_num)
        {
            upload_num[object_num]++;
            
            $('.counter:eq(' + object_num + ')').counter('update', upload_num[object_num]);
            
            return false;
        }
</script>

<br /><br />
<div id="view-content">
<!--	<p>View script for controller <b>File</b> and script/action name <b>collection</b></p>
        <p>ID: <?php echo $this->id ?></p>-->
        <!--<input type="button" onclick="update();return false;" value="Update"/>-->
    
        <h2>Kolekcja</h2>
        
        <h3><?php echo $this->user_name ?></h3>
        
        <p>
            <?php

            //init
            $i = 0;
            $object_num = 0;

            echo "<table>";

            //naglowek tablicy
            echo "<tr><th colspan=5></th><th>Pobrań<th></th><th></th></tr>";

            //sprawdzenie liczby plikow
            foreach($this->file_data as $file)
            {
                $i++;
            }

            //utowrzenie tablicy w js do przechowywania liczby pobran i dynamicznego ich zwiekszania
            echo "<script type=\"text/javascript\">
                        var upload_num = new Array(" . $i . ");
                    </script>";

            $i = 0;

            foreach($this->file_data as $file)
            {
                echo "<script type=\"text/javascript\">
                        upload_num[" . $object_num . "] = " . $file['ilosc_pobran'] . ";
                    </script>";

                echo "<tr><td><a href=\"" . $this->url(array('id' => $file['fileID']), 'file_download') . "\" onclick=\"update(" . $object_num . ");\" title=\"Kliknij, aby pobrać plik\">" . $file['nazwa'] . "</a></td><td>Format: " . $file['format'] . "</td><td>Wielkość: " . $file['waga'] . " MB</td>";

                if($file['format'] == "jpg" || $file['format'] == "JPG" || $file['format'] == "jpeg" || $file['format'] == "png")
                {
                    $image_size = getimagesize($file['url']);

                    echo "<td>Rozmiar: " . $image_size[0] . "x" . $image_size[1] . "</td>";
                    echo "<td><a href=\"" . $this->url(array('id' => $file['fileID'], 'ext' => $file['format']), 'file_show') . "\"><img id=\"thumb_" . $i . "\" src=\"" . $this->baseUrl('public/' . $file['url']) . "\" width=100 height=80 /></a></td>";
                }
                else
                {
                    echo "<td></td>";
                    echo "<td></td>";
                }

                //licznik pobran
                echo "<td><div class=\"counter\" name=\"" . $file['ilosc_pobran'] . "\"></div></td>";

                if(Zend_Auth::getInstance()->hasIdentity())
                {
                    if(($this->id == $this->user_id) || ($this->user_role == 'admin')) //widoczne tylko dla wlasciciela lub admina
                    {
                        //dla zdjec - edycja
                        if(($file['format'] == "jpg" || $file['format'] == "png") && $this->user_role == 'premium-user')
                        {
                            echo "<td><a class = \"admin-opt\" href = \"#\" onclick=\"return launchEditor('img_" . $i . "');\"><img src = \"" . $this->baseUrl("/public/styles/img/edit.png") . "\" alt = \"Edytuj\" /></a></td>";
                        }
                        else
                        {
                            echo "<td></td>";
                        }
                        echo "<td><a class = \"admin-opt\" href = \"" . $this->url(array('id' => $file['fileID']), 'file_delete') . "\"><img src = \"" . $this->baseUrl("/public/styles/img/delete.png") . "\" alt = \"Usuń\" /></a></td>";
                        echo "<td><img class=\"hidden\" id=\"img_" . $i . "\" src=\"" . $this->baseUrl('public/' . $file['url']) . "\" /></td>";
                        echo "</tr>";
                    }
                    else
                    {
                        echo "</tr>";
                    }

                    $i++;
                }

                $object_num++;
            }

            echo "</table>";

            ?>
            
        </p>
</div>

<div id = "album-options">
    <table>
        <tr>
            <?php
            //pobieranie w formie archiwum całego albumu
            echo "<td><a class = \"admin-opt\" href=\"" . $this->url(array('id' => $this->id, 'download' => 0), 'compress_all') . "\" title=\"Kompresuj pliki\"><img src=\"" . $this->baseUrl('public/styles/img/compress.png') . "\"</a></td>";
            ?>
        </tr>
    </table>
</div>